admins:
  terminalservers:
    - automator/admin@DCTI.SUT.RU
    - automator1/admin@DCTI.SUT.RU
    - automator2/admin@DCTI.SUT.RU
    - eshur@DCTI.SUT.RU
    - fhunter@DCTI.SUT.RU
    - op@DCTI.SUT.RU
    - Maxim_Rozhkov@DCTI.SUT.RU
  a445:
    - automator/admin@DCTI.SUT.RU
    - automator1/admin@DCTI.SUT.RU
    - automator2/admin@DCTI.SUT.RU
    - eshur@DCTI.SUT.RU
    - fhunter@DCTI.SUT.RU
    - hawk@DCTI.SUT.RU
    - op@DCTI.SUT.RU
    - Maxim_Rozhkov@DCTI.SUT.RU
  a439:
    - automator/admin@DCTI.SUT.RU
    - automator1/admin@DCTI.SUT.RU
    - automator2/admin@DCTI.SUT.RU
    - eshur@DCTI.SUT.RU
    - fhunter@DCTI.SUT.RU
    - op@DCTI.SUT.RU
    - Maxim_Rozhkov@DCTI.SUT.RU
  a425:
    - automator/admin@DCTI.SUT.RU
    - automator1/admin@DCTI.SUT.RU
    - automator2/admin@DCTI.SUT.RU
    - fhunter@DCTI.SUT.RU
    - hawk@DCTI.SUT.RU
    - op@DCTI.SUT.RU
    - eshur@DCTI.SUT.RU
    - Maxim_Rozhkov@DCTI.SUT.RU
  a233:
    - automator/admin@DCTI.SUT.RU
    - automator1/admin@DCTI.SUT.RU
    - automator2/admin@DCTI.SUT.RU
    - fhunter@DCTI.SUT.RU
    - hawk@DCTI.SUT.RU
    - op@DCTI.SUT.RU
    - eshur@DCTI.SUT.RU
    - Maxim_Rozhkov@DCTI.SUT.RU
  a42509.dcti.sut.ru:
    - a.seregin@DCTI.SUT.RU
  a443:
    - automator/admin@DCTI.SUT.RU
    - automator1/admin@DCTI.SUT.RU
    - automator2/admin@DCTI.SUT.RU
    - eshur@DCTI.SUT.RU
    - fhunter@DCTI.SUT.RU
    - op@DCTI.SUT.RU
    - Maxim_Rozhkov@DCTI.SUT.RU
  a441:
    - automator/admin@DCTI.SUT.RU
    - automator1/admin@DCTI.SUT.RU
    - automator2/admin@DCTI.SUT.RU
    - eshur@DCTI.SUT.RU
    - fhunter@DCTI.SUT.RU
    - op@DCTI.SUT.RU
    - Maxim_Rozhkov@DCTI.SUT.RU
